[app]
name = "YinYang"
category = "Badge"

[entry]
class = "YinYang"

[metadata]
author = "pikesley"
license = "MIT"
url = "https://www.github.com/pikesley/tildagon-yin-yang"
description = "YinYang"
version = "0.0.2"
